require('settings')
require('plugins')
require('mappings')
require('treesitter-config')
require('mason-config')
require('mason-lsp-config')
require('luasnip-config')
require('nvim-cmp-config')
require('lsp-config')
require('colorscheme-config.catppuccin')
require('comment-config')

vim.cmd("colorscheme catppuccin")
vim.cmd("hi Normal guibg=NONE ctermbg=NONE")
vim.cmd("hi NormalNC guibg=NONE ctermbg=NONE")
vim.cmd("hi SignColumn guibg=NONE ctermbg=NONE")
vim.cmd("hi VertSplit guibg=NONE ctermbg=NONE")
